[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Pandas = "eadc2687-ae89-51f9-a5d9-86b5a6373a9c"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlotly = "1f096619-141e-4d77-a13b-040156ae333b"
